---
title: "Análise dos 1000 filmes mais bem avaliados"
output: html_notebook
---

-----------------------

# 1 - Tratando os dados

----------------------

## 1.1 - Importando

```{r importando, echo=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(forcats)
library(stringr)

df <- read_csv("C:/Users/vmrod/Desktop/Repositorios/Portfolio/Analise_Filmes/imdb_top_1000.csv", show_col_types = FALSE)

```

---------------------------

## 1.2 - Compreendendo
```{r compreendendo}
glimpse(df)
```


A base de dados contém dados dos 1000 filmes mais bem avaliados segundo o Imdb.

Utilizando o comando glimpse podemos ter acesso às colunas da base.

* **Poster_Link**: Link para o poster do filme
* **Series_Title**: Nome do filme
* **Released_Year**: Ano que o filme foi lançado
* **Certificate**: Classificação indicativa
* **Runtime**: Duração do filme
* **Genre**: Gêneros do filme
* **IMDB_Rating**: Nota de acordo com o site IMDB que leva em conta a avaliação popular (Crítica não especializada)
* **Overview**: Descrição do filme
* **Meta_score**: Nota da crítica especializada
* **Director**: Nome do diretor
* **Star1-Star4**: Nome de atores principais
* **No_of_Votes**: Número de votos no site IMDB para o filme
* **Gross**: Faturamento bruto do filme

*Observando a descrição dos campos e os tipos de dados com glimpse vemos que temos que transformar os dados para facilitar a análise*

1. **Transformar a coluna Released_Year de caractere para numérico.**
2. **Transformar a coluna Runtime de caractere para numérico.**
3. **Transformar Certificate em um fator com um número de níveis menores.**
4. **Tratar a coluna Genre, pois é um caractere com vários gêneros separados por ,.**

-----------------------

## 1.3 - Transformando


-----------------------

### 1.3.1 - Released_Year | Caractere --> Numérico

```{r transformando Released_Year, echo=TRUE}
df <- df %>% mutate(Released_Year = parse_number(Released_Year))

```
Parse_number encontrou um erro na linha 967, pois encontrou os caracteres "PG" que não dá para converter para número. Vamos olhar a linha 967. 

```{r transformando Released_Year erro}
df[967,]
```

O filme da linha 967 é "Apollo 13", podemos descobrir o ano de lançamento dele no google e consertar esse erro.

```{r transformando Released_Year conserto}
df <- df %>% mutate(Released_Year = ifelse(Released_Year=="Apollo 13", 1995, Released_Year))

```

Substituindo o dado faltante pelo ano de lançamento de "Apollo 13" (1995), esta parte está concluída.

-----------------

### 1.3.2 - Runtime | Caractere --> Numérico

```{r Runtime}
df <- df %>% mutate(Runtime = parse_number(Runtime))

```

---------------

### 1.3.3 - Certificate | Organizando os níveis

```{r certificado}
levels(factor(df$Certificate))

```

Observando os possíveis certificados e fazendo uma pesquisa.

* https://en.wikipedia.org/wiki/Motion_picture_content_rating_system
* https://en.wikipedia.org/wiki/Television_content_rating_system
* https://en.wikipedia.org/wiki/Motion_Picture_Association_film_rating_system#From_M_to_GP_to_PG
* https://en.wikipedia.org/wiki/Central_Board_of_Film_Certification


Desconhecido | Brasil
------------ | -----------
16           |     16+

EUA | Brasil
----- | -----
G |L
PG, GP | 10+
PG-13 | 13+
R | 18+

EUA TV | Brasil
------ | -------
TV-PG | 10+
TV-14 | 14+
TV-MA | 18+

India | Brasil
------ | ------
U | L
UA, U/A | 12+
A | 18+

Inglaterra 1912-1932 | Brasil 
------ | --------
Passed | L
Approved | 16+


Agrupando eles em três grupos:

* L, 12+, 16+

```{r certificado organizando}
df <- df %>% mutate(Certificate=factor(Certificate))

df <- df %>% mutate(Certificate=fct_collapse(Certificate,
                                           "L"=c("G","PG","GP",
                                              "TV-PG","U","Passed"),"12+"=c("PG-13", "TV-14","UA","U/A"),
  "16+"=c("A","Approved","TV-MA","R","16"),NULL=c("Unrated")))

df <- df %>% mutate(Certificate=factor(Certificate,levels=c("L","12+","16+")))
                                       
```

--------

### 1.3.4 - Genre | Separando

Um filme pode ter mais de um gênero, por isso a coluna Genre pode ter até três gêneros por célula, separados por vírgula. Para filmes com mais de um gênero, vamos separar os gêneros em linhas. Por exemplo, se um filme é de Ação, Aventura e Sci-Fi, terá três linhas, um para cada gênero. 

Vamos criar um data frame novo para isso, pois isso irá aumentar o número de linhas, logo dependendo de quais variáveis quisermos analisar, será melhor usar o data frame original.


```{r genero}
df_genero <- df %>% separate_rows(Genre, sep=",") %>%
  mutate(Genre=str_trim(Genre))

```

Por enquanto essas transformações serão suficientes, mais à frente faremos mais a fim de analisar também os atores.

-------
